### Q1. List any five functions of the pandas library with execution.

#### Five functions:-
1.head() & tail() : To get first and last few records from a dataframe respectively.
<br>
2.shape() : To get the dimension of the dataframe
<br>
3.info() :  To get a consise summary of dataframe
<br>
4.describe() : To get summary statistics of dataframe.
<br>
5.sort_values() : To sort the DataFrame by the values of one or more columns.

In [1]:
# creating sample dataset 

import pandas as pd

df_1 = pd.DataFrame(
    {
    'RollNo':['1001','1002','1003','1004','1005','1006','1007','1008'],
    'Name' : ['Alice', 'Jane', 'Kurtis', 'Ember', 'Flora', 'Genelia', 'Ikea', 'Hamie'],
    'Marks_in_CS' : [56,57,98,67,25,99,65,45],
    'Marks_in_Maths' : [76,89,87,45,77,56,97,56],
    'Marks_in_Eng': [45,89,45,88,65,88,34,53]
    }
)

In [2]:
# 1. Head() and Tail()

# to obtain first 3 records
df_1.head(3)

  RollNo    Name  Marks_in_CS  Marks_in_Maths  Marks_in_Eng
0   1001   Alice           56              76            45
1   1002    Jane           57              89            89
2   1003  Kurtis           98              87            45

In [3]:
# to obtain last 3 records
df_1.tail(3)

  RollNo     Name  Marks_in_CS  Marks_in_Maths  Marks_in_Eng
5   1006  Genelia           99              56            88
6   1007     Ikea           65              97            34
7   1008    Hamie           45              56            53

In [4]:
# 2.shape

df_1.shape

(8, 5)

In [5]:
# 3.info

df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   RollNo          8 non-null      object
 1   Name            8 non-null      object
 2   Marks_in_CS     8 non-null      int64
 3   Marks_in_Maths  8 non-null      int64
 4   Marks_in_Eng    8 non-null      int64
dtypes: int64(3), object(2)
memory usage: 448.0+ bytes

In [6]:
# 4.describe()

df_1.describe()

       Marks_in_CS  Marks_in_Maths  Marks_in_Eng
count     8.000000        8.000000      8.000000
mean     64.000000       72.875000     63.375000
std      25.031409       18.573695     22.417707
min      25.000000       45.000000     34.000000
25%      53.250000       56.000000     45.000000
50%      61.000000       76.500000     59.000000
75%      74.750000       87.500000     88.000000
max      99.000000       97.000000     89.000000

In [7]:
# 5.sort_value()

df_1.sort_values(by=['Marks_in_CS'], ascending=False)

  RollNo     Name  Marks_in_CS  Marks_in_Maths  Marks_in_Eng
5   1006  Genelia           99              56            88
2   1003   Kurtis           98              87            45
3   1004    Ember           67              45            88
6   1007     Ikea           65              97            34
1   1002     Jane           57              89            89
0   1001    Alice           56              76            45
7   1008    Hamie           45              56            53
4   1005    Flora           25              77            65

### Q2. Given a Pandas DataFrame df with columns 'A', 'B', and 'C', write a Python function to re-index the DataFrame with a new index that starts from 1 and increments by 2 for each row.

In [8]:
#creating a sample dataframe

df= pd.DataFrame(
        {
        'A':[1,2,3,4,5],
        'B':['abc','def','ghi','jkl','mno'],
        'C':[1,0,1,1,0]
        }
)

new_index= pd.Index(range(0,len(df)*2,2))

df_reindexed= df.set_index(new_index)

In [9]:
df_reindexed

   A    B  C
0  1  abc  1
2  2  def  0
4  3  ghi  1
6  4  jkl  1
8  5  mno  0

### Q3. You have a Pandas DataFrame df with a column named 'Values'. Write a Python function that iterates over the DataFrame and calculates the sum of the first three values in the 'Values' column. The function should print the sum to the console.

In [10]:
df= pd.DataFrame(
        {
        'Item':[1,2,3,4,5],
        'Name':['abc','def','ghi','jkl','mno'],
        'Values':[10,20,30,40,50]
        }
)

def df_sum3(df):
    if 'Values' not in df.columns:
        return " 'Values' column not found"
     
    sumf3 = df['Values'].iloc[:3].sum()
    
    return f"Sum of the first 3 values in 'Values' column: {sumf3}"
    

df_sum3(df)

"Sum of the first 3 values in 'Values' column: 60"

In [11]:
# Aliter

def df_sum3(df):
    s=0
    found=True
    
    for i in df.columns:
        if(i=='Values'):
            found=False
            for j in df['Values'].iloc[:3]:
                s+=j
    if found:
        return f"Values Column not Found"
    
    return f"Sum of first 3 values in 'Values' columns : {s} "

df_sum3(df)

"Sum of first 3 values in 'Values' columns : 60 "

### Q4. Given a Pandas DataFrame df with a column 'Text', write a Python function to create a new column 'Word_Count' that contains the number of words in each row of the 'Text' column.

In [12]:
df= pd.DataFrame(
    {
    'Text':
        ['An Apple a day keeps the doctor away.',
         'Eating pineapple may help boost immunity.',
         'Eating watermelon promotes good health.']     
    }
)

def new_wc(df):
    lst=[]
    for i in range(len(df)):
        wc=len(df['Text'][i].split())
        lst.append(wc)
    
    df['Word_Count']=lst
    return df


new_wc(df)

                                        Text  Word_Count
0      An Apple a day keeps the doctor away.           8
1  Eating pineapple may help boost immunity.           6
2    Eating watermelon promotes good health.           5

In [13]:
# aliter

import pandas as pd

df = pd.DataFrame({
    'Text': [
        'An Apple a day keeps the doctor away',
        'Eating pineapple may help boost immunity',
        'Eating watermelon promotes good health'
    ]
})

def count_words(text):
    # Split the text into words and count them
    return len(text.split())

# Apply the function to create the 'Word_Count' column
df['Word_Count'] = df['Text'].apply(count_words)

# Display the updated DataFrame
print(df)

                                       Text  Word_Count
0      An Apple a day keeps the doctor away           8
1  Eating pineapple may help boost immunity           6
2    Eating watermelon promotes good health           5

### Q5. How are DataFrame.size() and DataFrame.shape() different?

| Attribute        | Description                                                                                                                                                                                                                   | Usage                                                                                          |
|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|
| `DataFrame.size` | Total number of elements (cells) in the DataFrame, calculated as the product of the number of rows and columns.                                                                                                              | Provides the total count of all elements in the DataFrame.                                     |
| `DataFrame.shape`| Tuple representing the dimensions of the DataFrame, where the first element is the number of rows and the second element is the number of columns.                                                                        | Commonly used to determine the structure (number of rows and columns) of the DataFrame.        |

### Q6. Which function of pandas do we use to read an excel file?

We use ' `pd.read_csv("sample_fileName.csv")` ' function to read a csv file.

### Q7. You have a Pandas DataFrame df that contains a column named 'Email' that contains email addresses in the format 'username@domain.com' . Write a Python function that creates a new column 'Username' in df that contains only the username part of each email address.

#### The username is the part of the email address that appears before the '@' symbol. For example, if the email address is 'john.doe@example.com', the 'Username' column should contain 'john.doe'. Your function should extract the username from each email address and store it in the new 'Username' column.

In [14]:
df=pd.DataFrame({
        'Email' : [
                    'john.doe@example.com',
                    'margha@sample.com',
                    'janeblue@ghail.com',
                    'tanmay_sharma@newmail.com',
                    'genilia.gim@catmail.com']

})

# defining the function
def new_col_username(df):
    unames=[]
    for i in df['Email']:
        unames.append(i.split('@')[0])
    df['Username']=unames
    return df

# calling the function
new_col_username(df)

                       Email       Username
0       john.doe@example.com       john.doe
1          margha@sample.com         margha
2         janeblue@ghail.com       janeblue
3  tanmay_sharma@newmail.com  tanmay_sharma
4    genilia.gim@catmail.com    genilia.gim

In [15]:
# Aliter

df=pd.DataFrame({
        'Email' : [
                    'john.doe@example.com',
                    'margha@sample.com',
                    'janeblue@ghail.com',
                    'tanmay_sharma@newmail.com',
                    'genilia.gim@catmail.com']
})

# defining function to get username and create a new column for it
def username(df):
    # Using the .str accessor for vectorized string operations
    df['Username']=df['Email'].str.split('@').str[0]
    return df

# defining function to get domain names
def email_domain(df):
    temp=df["Email"].str.split('@').str[1]
    df['Domain_Name']=temp.str.split('.com').str[0]
    return df

print(username(df),'\n\n')
print(email_domain(df))

                       Email       Username
0       john.doe@example.com       john.doe
1          margha@sample.com         margha
2         janeblue@ghail.com       janeblue
3  tanmay_sharma@newmail.com  tanmay_sharma
4    genilia.gim@catmail.com    genilia.gim


                       Email       Username Domain_Name
0       john.doe@example.com       john.doe     example
1          margha@sample.com         margha      sample
2         janeblue@ghail.com       janeblue       ghail
3  tanmay_sharma@newmail.com  tanmay_sharma     newmail
4    genilia.gim@catmail.com    genilia.gim     catmail


### Important Concept- Vectorized Operations

[Read_More](https://towardsdatascience.com/pandas-dtype-specific-operations-accessors-c749bafb30a4)
<br>
**The .str accessor in pandas allows for vectorized string operations on Series objects. This means you can perform common string operations on all elements of a Series simultaneously, without needing to loop through each element individually.**

<br>

pandas provides several other accessors similar to `.str` that allow you to perform specialized operations on specific data types within a DataFrame or Series. Here are some of the most commonly used accessors:

<br>

Pandas provides these accessors to facilitate operations on specific data types, making it easier to manipulate, analyze, and visualize data in a more concise and efficient manner. Here’s a quick overview:

<br>

| **Accessor** | **Usage**                                 | **Example Operations**                                                                                  |
|--------------|-------------------------------------------|---------------------------------------------------------------------------------------------------------|
| `.str`       | String operations                        | Splitting, replacing, converting to lowercase/uppercase, extracting substrings                          |
| `.dt`        | Datetime operations                      | Extracting year, month, day, hour, minute, second, week, weekday, calculating differences, truncating   |
| `.cat`       | Categorical operations                   | Adding, removing, renaming categories, reordering categories, checking category properties              |
| `.sparse`    | Sparse data operations                   | Converting to dense, accessing underlying data                                                          |
| `.plot`      | Plotting and visualization               | Creating line plots, bar plots, histograms, scatter plots, box plots                                     |

These accessors enhance the flexibility and power of pandas for data analysis and manipulation.

In [16]:
# example of .dt accessor

import pandas as pd

# Sample DataFrame with datetime values
df = pd.DataFrame({
    'Date': pd.to_datetime([
        '2021-01-01', '2021-02-15', '2021-03-10', '2021-04-25', '2021-05-30'
    ])
})

# Extracting year, month, day
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

print(df)

        Date  Year  Month  Day
0 2021-01-01  2021      1    1
1 2021-02-15  2021      2   15
2 2021-03-10  2021      3   10
3 2021-04-25  2021      4   25
4 2021-05-30  2021      5   30

### Q8. You have a Pandas DataFrame df with columns 'A', 'B', and 'C'. Write a Python function that selects all rows where the value in column 'A' is greater than 5 and the value in column 'B' is less than 10. The function should return a new DataFrame that contains only the selected rows.df[(df['A']>5) & (df['B']<10)]

In [17]:
df=pd.DataFrame({
    'A':[3,8,6,2,9],
    'B':[5,2,9,3,1],
    'C':[1,7,4,5,2]
})

#defining function
def fun_filter_rows(df):
    return df[(df['A']>5) & (df['B']<10)]

# calling function
fun_filter_rows(df)

   A  B  C
1  8  2  7
2  6  9  4
4  9  1  2

### Q9. Given a Pandas DataFrame df with a column 'Values', write a Python function to calculate the mean, median, and standard deviation of the values in the 'Values' column.

In [18]:
df=pd.DataFrame({
    'Values': [1,2,3,4,5,6,7,8,9,10]
})

def fun_stat(df):
    print("Mean of the 'Values' column : ",df['Values'].mean())
    print("\nMedian of the 'Values' column : ",df['Values'].median())
    print("\nStandard Deviation of the 'Values : ' column",df['Values'].std())
    return None

fun_stat(df)

Mean of the 'Values' column :  5.5

Median of the 'Values' column :  5.5

Standard Deviation of the 'Values : ' column 3.0276503540974917

In [19]:
# to cross check
df.describe()

         Values
count  10.00000
mean    5.50000
std     3.02765
min     1.00000
25%     3.25000
50%     5.50000
75%     7.75000
max    10.00000

### Q10. Given a Pandas DataFrame df with a column 'Sales' and a column 'Date', write a Python function to create a new column 'MovingAverage' that contains the moving average of the sales for the past 7 days for each row in the DataFrame. The moving average should be calculated using a window of size 7 and should include the current day.

In [20]:
# Sample DataFrame
data = {
    'Date': pd.date_range(start='2023-01-01', periods=15, freq='D'),
    'Sales': [100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800]
}
df = pd.DataFrame(data)

# Ensure the DataFrame is sorted by date
df.sort_values(by='Date', inplace=True)

# Defining the function to calculate the 7-day moving average
def add_moving_average(df):
    df['MovingAverage'] = df['Sales'].rolling(window=7, min_periods=1).mean()
    return df

# Calling the function
df = add_moving_average(df)

# Displaying the DataFrame
print(df)

         Date  Sales  MovingAverage
0  2023-01-01    100          100.0
1  2023-01-02    150          125.0
2  2023-01-03    200          150.0
3  2023-01-04    250          175.0
4  2023-01-05    300          200.0
5  2023-01-06    350          225.0
6  2023-01-07    400          250.0
7  2023-01-08    450          300.0
8  2023-01-09    500          350.0
9  2023-01-10    550          400.0
10 2023-01-11    600          450.0
11 2023-01-12    650          500.0
12 2023-01-13    700          550.0
13 2023-01-14    750          600.0
14 2023-01-15    800          650.0

### Q11. You have a Pandas DataFrame df with a column 'Date'. Write a Python function that creates a new column 'Weekday' in the DataFrame. The 'Weekday' column should contain the weekday name (e.g. Monday, Tuesday) corresponding to each date in the 'Date' column.

In [21]:
# Sample DataFrame
data = {
    'Date': pd.date_range(start='2024-07-01', periods=7, freq='D')
}
df = pd.DataFrame(data)

# Defining the function to add the 'Weekday' column
def add_weekday_column(df):
    df['Weekday'] = df['Date'].dt.day_name()
    return df

# Calling the function
df = add_weekday_column(df)

# Displaying the DataFrame
print(df)

        Date    Weekday
0 2024-07-01     Monday
1 2024-07-02    Tuesday
2 2024-07-03  Wednesday
3 2024-07-04   Thursday
4 2024-07-05     Friday
5 2024-07-06   Saturday
6 2024-07-07     Sunday

### Q12. Given a Pandas DataFrame df with a column 'Date' that contains timestamps, write a Python function to select all rows where the date is between '2023-01-01' and '2023-01-31'.

**notes**
- `df.loc` is a primary attribute in pandas used for selecting rows and columns from a DataFrame by label-based indexing.
- syntax `df.loc[row_labels, column_labels]`

In [22]:
# Sample DataFrame
data = {
    'Date': pd.date_range(start='2023-01-01', periods=50, freq='D')
}
df = pd.DataFrame(data)

# Defining the function to filter rows based on date range
def filter_by_date(df):
    start_date = '2023-01-01'
    end_date = '2023-01-31'
    mask = (df['Date'] >= start_date) & (df['Date'] <= end_date)
    filtered_df = df.loc[mask]
    return filtered_df

# Calling the function
filtered_df = filter_by_date(df)

# Displaying the filtered DataFrame
print(filtered_df)

         Date
0  2023-01-01
1  2023-01-02
2  2023-01-03
3  2023-01-04
4  2023-01-05
5  2023-01-06
6  2023-01-07
7  2023-01-08
8  2023-01-09
9  2023-01-10
10 2023-01-11
11 2023-01-12
12 2023-01-13
13 2023-01-14
14 2023-01-15
15 2023-01-16
16 2023-01-17
17 2023-01-18
18 2023-01-19
19 2023-01-20
20 2023-01-21
21 2023-01-22
22 2023-01-23
23 2023-01-24
24 2023-01-25
25 2023-01-26
26 2023-01-27
27 2023-01-28
28 2023-01-29
29 2023-01-30
30 2023-01-31

### Q13. To use the basic functions of pandas, what is the first and foremost necessary library that needs to be imported?

"Pandas"<br>
using `import pandas as pd`<br>
where pd is alias

## extras
The `pd.date_range()` function in pandas is used to generate a fixed-frequency DatetimeIndex. It's a versatile tool for creating date and time sequences, which is essential for working with time series data in pandas.

### Syntax:
```python
pd.date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize=False, name=None, closed=None, **kwargs)
```

### Parameters:

- **`start`**: Start date for the range. If not specified, defaults to `None`.
- **`end`**: End date for the range. If not specified, defaults to `None`.
- **`periods`**: Number of periods (e.g., days) to generate. Specify either `end` or `periods`, but not both.
- **`freq`**: Frequency strings or DateOffset objects specifying the frequency of the dates to be generated. This is a required parameter if `start` and `end` are not specified.
- **`tz`**: Time zone name for the DatetimeIndex. Default is `None` (no timezone).
- **`normalize`**: If True, normalize the start and end dates to midnight before generating the date range.
- **`name`**: Name to be stored in the resulting DatetimeIndex.
- **`closed`**: Defines whether to include `start` and `end` dates. Possible values are 'right', 'left', 'both', 'neither'. Default is `None`.

### Frequencies (`freq` parameter):
The `freq` parameter allows you to specify the frequency of the dates to be generated. Some common frequency strings include:

- **`'D'`**: calendar day frequency
- **`'B'`**: business day frequency
- **`'W'`**: weekly frequency
- **`'M'`**: month end frequency
- **`'Q'`**: quarter end frequency
- **`'A'`**: year end frequency

These can be combined with numbers to specify multiples, e.g., `'3D'` for every 3 days, `'2W'` for every 2 weeks.

In [23]:
import pandas as pd

# Generate a date range from '2023-01-01' to '2023-01-31'
date_range = pd.date_range(start='2023-01-01', end='2023-01-31')
print(date_range)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31'],
              dtype='datetime64[ns]', freq='D')

In [25]:
# Generate a date range with a weekly frequency starting from '2023-01-01'
weekly_range = pd.date_range(start='2023-01-01', periods=13, freq='W')
print(weekly_range)

DatetimeIndex(['2023-01-01', '2023-01-08', '2023-01-15', '2023-01-22',
               '2023-01-29', '2023-02-05', '2023-02-12', '2023-02-19',
               '2023-02-26', '2023-03-05', '2023-03-12', '2023-03-19',
               '2023-03-26'],
              dtype='datetime64[ns]', freq='W-SUN')